# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable non-transitive R classes for smaller APK
android.nonTransitiveRClass=true

# Enable build cache
org.gradle.caching=true

# Enable parallel execution
org.gradle.parallel=true

# Enable configuration cache
org.gradle.configuration-cache=true
